// NeturionJobBoard Contract
export const NETURION_JOB_BOARD = "0x1efb0d6f35a0556cd940769941a84e36926a418a" as `0x\${string}`

export const JOB_BOARD_ABI = [
  { name: "postJob", type: "function", stateMutability: "nonpayable",
    inputs: [
      { name: "provider", type: "address" },
      { name: "description", type: "string" },
      { name: "budget", type: "uint256" },
    ], outputs: [{ name: "", type: "uint256" }] },
  { name: "registerAgent", type: "function", stateMutability: "nonpayable",
    inputs: [
      { name: "agentId", type: "uint256" },
      { name: "name", type: "string" },
      { name: "role", type: "string" },
    ], outputs: [] },
  { name: "completeJob", type: "function", stateMutability: "nonpayable",
    inputs: [{ name: "jobId", type: "uint256" }], outputs: [] },
  { name: "cancelJob", type: "function", stateMutability: "nonpayable",
    inputs: [{ name: "jobId", type: "uint256" }], outputs: [] },
  { name: "getJob", type: "function", stateMutability: "view",
    inputs: [{ name: "jobId", type: "uint256" }],
    outputs: [{ name: "", type: "tuple", components: [
      { name: "id", type: "uint256" },
      { name: "client", type: "address" },
      { name: "provider", type: "address" },
      { name: "description", type: "string" },
      { name: "budget", type: "uint256" },
      { name: "createdAt", type: "uint256" },
      { name: "status", type: "uint8" },
    ]}] },
  { name: "getAgent", type: "function", stateMutability: "view",
    inputs: [{ name: "owner", type: "address" }],
    outputs: [{ name: "", type: "tuple", components: [
      { name: "agentId", type: "uint256" },
      { name: "owner", type: "address" },
      { name: "name", type: "string" },
      { name: "role", type: "string" },
      { name: "jobsCompleted", type: "uint256" },
      { name: "totalEarned", type: "uint256" },
      { name: "registered", type: "bool" },
    ]}] },
  { name: "getStats", type: "function", stateMutability: "view",
    inputs: [], outputs: [
      { name: "totalJobs", type: "uint256" },
      { name: "totalAgents", type: "uint256" },
    ] },
  { name: "getClientJobs", type: "function", stateMutability: "view",
    inputs: [{ name: "client", type: "address" }],
    outputs: [{ name: "", type: "uint256[]" }] },
  { name: "getProviderJobs", type: "function", stateMutability: "view",
    inputs: [{ name: "provider", type: "address" }],
    outputs: [{ name: "", type: "uint256[]" }] },
  { name: "jobCount", type: "function", stateMutability: "view",
    inputs: [], outputs: [{ name: "", type: "uint256" }] },
  { name: "agentCount", type: "function", stateMutability: "view",
    inputs: [], outputs: [{ name: "", type: "uint256" }] },
  { name: "JobPosted", type: "event",
    inputs: [
      { name: "jobId", type: "uint256", indexed: true },
      { name: "client", type: "address", indexed: true },
      { name: "budget", type: "uint256", indexed: false },
      { name: "description", type: "string", indexed: false },
    ] },
  { name: "JobCompleted", type: "event",
    inputs: [
      { name: "jobId", type: "uint256", indexed: true },
      { name: "provider", type: "address", indexed: true },
      { name: "earned", type: "uint256", indexed: false },
    ] },
  { name: "AgentRegistered", type: "event",
    inputs: [
      { name: "owner", type: "address", indexed: true },
      { name: "agentId", type: "uint256", indexed: false },
      { name: "name", type: "string", indexed: false },
      { name: "role", type: "string", indexed: false },
    ] },
] as const
